/*INSERT INTO media VALUES ('1','dolore','/change-log/changes/static/bestseller.jpg'),
('2','molestias','/change-log/changes/static/cart.jpg'),
('3','molestias','/change-log/changes/static/cart.png'),
('4','quo','/changes/static/exit.jpg'),
('5','debitis','/changes/static/other.png'),
('6','unde','/changes/static/product.png'),
('7','voluptas','/changes/static/report.png'),
('8','id','/changes//static/table.jpg'),
('9','voluptatem','/changes/static/user.png'),
('10','iste','/changes//static/newproduct.png');

INSERT INTO media VALUES('12','NEW','C:/Users/furkanekim/Desktop/sheets/user.png');*/


INSERT INTO product VALUES ('51','et','Sed ea ratione laborum quas distinctio dolor. Faci','20','http://glover.biz/','8'),
('52','alias','Voluptatem quis eaque quisquam ut maiores similiqu','1','http://koelpinwaters.com/','7'),
('53','at','Dolor et natus consequatur voluptate minima illum.','1','http://smitham.com/','7'),
('54','doloribus','Qui occaecati totam aut ut nisi alias rerum. Quia ','84','http://www.buckridgedaniel.biz/','4'),
('55','quis','Minima facilis optio et est qui autem. Quo eum nis','12','http://www.leuschke.com/','7'),
('57','totam','Voluptas perferendis quidem amet labore. Aperiam e','11','http://auer.com/','7'),
('58','numquam','Voluptatem ab ut officiis cumque autem beatae volu','3','http://www.larkin.com/','7'),
('59','veritatis','Neque non voluptatem cum accusamus est. Ut nobis r','1','http://effertzkris.info/','9'),
('60','dolorem','Rem earum et aut eius. Magnam expedita possimus eu','59','http://www.bayer.com/','3'),
('61','odit','At aperiam asperiores quidem eveniet quis eaque es','6','http://considine.info/','7'),
('62','vero','Molestias dolore tenetur molestiae. Facilis tempor','17','http://yundt.com/','8'),
('63','autem','Commodi sed fugit repellendus. Veniam non rerum it','40','http://schmitt.com/','7'),
('64','et','Similique iste magni assumenda. Ea et est autem qu','44','http://www.homenick.com/','2'),
('65','fugiat','Aliquam culpa ad et ipsa pariatur sed cumque. A qu','26','http://www.schulist.com/','8'),
('66','ratione','Voluptatem at id qui quod qui quos. Qui quisquam r','43','http://jaskolskijaskolski.com/','7'),
('67','quisquam','Dolorum pariatur aut aperiam omnis doloremque inci','11','http://larkin.org/','7'),
('68','fuga','Ipsum quos provident sint nobis. Ut qui sunt verit','40','http://www.oconnercrona.com/','5'),
('69','laborum','Consectetur beatae enim est soluta quae. Doloribus','4','http://www.maggioprosacco.com/','8'),
('70','rerum','Fugiat nulla illo consequatur qui quod. Perferendi','30','http://www.armstrongchamplin.com/','8'),
('72','quas','Inventore earum exercitationem voluptas. Facilis f','2','http://conroykuhlman.com/','4'),
('73','est','Tempore accusamus corporis vel inventore deserunt ','25','http://www.gaylordspinka.biz/','3'),
('75','aut','Doloribus autem natus minus. Ipsum dolores totam i','56','http://nitzsche.com/','1'),
('76','voluptas','Molestiae laboriosam soluta cum temporibus. Porro ','22','http://www.willms.net/','9'),
('77','aliquam','Et doloremque corporis praesentium doloribus volup','41','http://feeney.biz/','8'),
('78','et','Ut aspernatur ipsum animi sunt sed. Ea voluptas et','10','http://www.towne.com/','3'),
('80','cupiditate','Unde ad ratione rem aut quo. Laborum quidem dolor ','30','http://dickens.com/','3'),
('81','consequatur','Doloremque voluptas nulla dolores perspiciatis. Re','4','http://www.oreillyziemann.com/','7'),
('82','aut','Nemo sapiente ut quidem cum praesentium. Ratione e','90','http://www.moore.org/','2'),
('83','sed','Eveniet beatae distinctio eum architecto facilis. ','27','http://rosenbaumnicolas.com/','7'),
('84','hic','Dolores dicta fuga corporis ullam aut qui eos. Tem','30','http://www.jacobi.org/','9'),
('85','dicta','Impedit est quo optio qui soluta et consequuntur v','78','http://www.turcotte.com/','9'),
('87','reprehenderit','Est sed aut officia tenetur. Distinctio laborum pa','7','http://www.ondricka.com/','2'),
('88','doloremque','Aut qui laborum rerum sint. Quis aperiam quae nobi','1','http://swaniawskimcdermott.net/','3'),
('89','aperiam','Explicabo similique a in et. Qui est illum laborio','40','http://www.prosacco.org/','4'),
('90','deserunt','Autem nam distinctio et id ut molestias corrupti. ','12','http://www.pouros.com/','7'),
('91','dicta','Velit accusamus voluptate quaerat. Aut eius occaec','8','http://hilpert.org/','6'),
('92','facilis','Sunt totam id rerum natus ratione quidem expedita.','4','http://www.connelly.com/','1'),
('93','quia','Hic enim ipsa qui qui. Quia sit sit esse ut conseq','20','http://www.becker.info/','1'),
('94','sed','Et voluptatem deleniti consequatur iste ut maxime ','2','http://gibson.com/','5'),
('95','nam','Minus dolorem veritatis et quod est temporibus. Qu','5','http://strosin.com/','8'),
('96','nam','Doloremque saepe tempora blanditiis facilis tempor','54','http://greenholt.info/','2'),
('97','quos','Eos praesentium quia commodi. Voluptatem ratione i','1','http://www.oconnell.biz/','6'),
('98','sit','Aut cupiditate similique qui et nobis et at sapien','1','http://www.bode.com/','5'),
('99','ducimus','Hic ab laboriosam dolor. Alias nesciunt aut nihil ','31','http://www.wisoky.com/','6'),
('100','ad','Id culpa quo nesciunt odio praesentium voluptate n','8','http://www.kuphal.com/','4');


INSERT INTO category VALUES ('1','minus','Aut et maxime saepe aliquam. Saepe et vero in aper','http://www.uptonconsidine.com/','1'),
('2','sed','Ut maxime qui facere ex ratione. Placeat accusamus','http://bosco.com/','2'),
('3','officiis','Atque quo eveniet magni. Non voluptates et nihil. ','http://www.harber.biz/','3'),
('4','quos','Ut deserunt excepturi impedit in saepe. Ad alias i','http://www.stracke.org/','4'),
('5','et','Ut consequatur similique corporis iste unde dolore','http://dickinson.com/','5'),
('6','sit','Quasi sint qui accusantium necessitatibus nihil vo','http://daniel.net/','6'),
('7','soluta','Nesciunt voluptatem repellendus consequatur qui et','http://www.strackeluettgen.biz/','7'),
('8','dolores','Quia quo autem cupiditate est id. Qui quisquam vol','http://www.dare.com/','8'),
('9','distinctio','Quis dignissimos eveniet nihil in iusto explicabo.','http://kozeyabbott.biz/','9'),
('10','architecto','Sapiente inventore temporibus ipsum consequatur. E','http://goldner.com/','10'),
('11','provident','Nihil quam ex et et fugit. Eaque est aut et sunt s','http://welch.com/','1'),
('12','quo','Aspernatur eum nesciunt ea fuga ab itaque. Consect','http://www.fritsch.com/','2'),
('13','possimus','Id qui qui ex occaecati doloremque dolorem qui. Al','http://cruickshankbrown.org/','3'),
('14','cumque','Minus dolorem error veritatis quis natus hic. Omni','http://funk.com/','4'),
('15','nobis','In atque repudiandae quia doloribus optio nihil pr','http://www.kihn.com/','5'),
('16','nesciunt','Adipisci necessitatibus molestiae dolorem illo con','http://www.mcclurebrekke.biz/','6'),
('17','aliquid','Illum nisi est ut omnis adipisci nam. Repellat id ','http://dickinson.com/','7'),
('18','eveniet','Voluptatem sit velit explicabo. Non quos aperiam i','http://www.predovicwisoky.biz/','8'),
('19','impedit','Voluptas officia aperiam pariatur eius temporibus ','http://zieme.biz/','9'),
('20','id','Ut voluptatum iure distinctio eveniet numquam volu','http://www.wiegand.com/','10');


INSERT INTO category_products VALUES ('1','51'),
('1','67'),
('1','73'),
('1','91'),
('1','96'),
('2','52'),
('2','68'),
('2','75'),
('2','92'),
('2','97'),
('3','53'),
('3','69'),
('3','76'),
('3','93'),
('3','98'),
('4','54'),
('4','70'),
('4','77'),
('4','94'),
('4','99'),
('5','55'),
('5','72'),
('5','78'),
('5','95'),
('5','100'),
('6','51'),
('6','57'),
('6','73'),
('6','80'),
('6','96'),
('7','52'),
('7','58'),
('7','75'),
('7','81'),
('7','97'),
('8','53'),
('8','59'),
('8','76'),
('8','82'),
('8','98'),
('9','54'),
('9','60'),
('9','77'),
('9','83'),
('9','99'),
('10','55'),
('10','61'),
('10','78'),
('10','84'),
('10','100'),
('11','51'),
('11','57'),
('11','62'),
('11','80'),
('11','85'),
('12','52'),
('12','58'),
('12','63'),
('12','81'),
('12','87'),
('13','53'),
('13','59'),
('13','64'),
('13','82'),
('13','88'),
('14','54'),
('14','60'),
('14','65'),
('14','83'),
('14','89'),
('15','55'),
('15','61'),
('15','66'),
('15','84'),
('15','90'),
('16','57'),
('16','62'),
('16','67'),
('16','85'),
('16','91'),
('17','58'),
('17','63'),
('17','68'),
('17','87'),
('17','92'),
('18','59'),
('18','64'),
('18','69'),
('18','88'),
('18','93'),
('19','60'),
('19','65'),
('19','70'),
('19','89'),
('19','94'),
('20','61'),
('20','66'),
('20','72'),
('20','90'),
('20','95');

INSERT INTO place_rest(id,name,table_piece,media_id)
values ('1','INDOOR','13',1),
('2','OUTDOOR','12',2),
('3','TERRACE','15',3);

INSERT INTO roles(id,name)
values('1','ROLE_USER'),
('2','ROLE_ADMIN');

INSERT INTO users(id,username,email,password)
values('1','user','email','$2y$12$ldrSe6bsZoc0C1xyr0q3DuJztDUJ0LNiQOJKCcCkK98t.FZJiomDm'),
('2','admin','email','$2y$12$ldrSe6bsZoc0C1xyr0q3DuJztDUJ0LNiQOJKCcCkK98t.FZJiomDm');

INSERT INTO user_roles(USER_ID,ROLE_ID)
values('2','1'),('2','2'),('1','1');

